### PR TITLE
[ABONDONED] Add Omnidu support

### PR DESCRIPTION
**Pull request by sn3p**
This adds [Omnidu](http://www.omnidu.nl) engine and template to Onebox.
Didn't write any tests because I couldn't get them running :(

**Example Omnidu player URL:**
http://omnidustaging.omnidu.nl/app/player.aspx?dl=0126a854-03e3-4d03-bba4-304063603242

---

The [first commit](d5df3548b462aa458202447a5400ff45f5048327) is build and based on **v1.8.1**. But since this is fork is still at **v1.5.22** I had to make some adjustments to get it to work.

Maybe we can get this fork up to date first and skip the [second commit](d5df3548b462aa458202447a5400ff45f5048327)?

### CODE REVIEW

**Comment by tarzan** [comment]
yeah, let me rebase this fork

**Comment by tarzan** [comment]
done. plz rebase :D

**Comment by sn3p** [comment]
@tarzan done!

We are currently accepting `http` urls for `*.omnidu.nl/app/player*`. Could that be a security risk?

---

**Also**, the updated Onebox added some new engines/templates. On if them is [pdf_onebox.rb](https://github.com/tarzan/onebox/blob/master/lib/onebox/engine/pdf_onebox.rb) which Oneboxes PDF files only when the url starts with `https://`.

screen shot 2017-02-12 at 16 44 46

For PDFs from `http://` it throws an error:

> POST http://defacto.learningspaces.dev/api/v1/onebox 404 (Not Found)

Kinda wonky :( Also I'm having some concerns, because this will break existing inline `https://*.pdf` links (within a sentence for example). Might not be a big problem though.

**A few options:**

1. Leave this as is for now.

2. Disable (remove) the PDF engine.

3. Enable PDF engine for `http` and `https`
   ```rb
   matches_regexp(/^https?:\/\/.*\.pdf(\?.*)?$/i)
   ```

4. Only accept `https` without errors:
   ```rb
   matches_regexp(/^https:\/\/.*\.pdf(\?.*)?$/i)
   always_https
   ```
What do you prefer?

**Comment by sn3p** [comment]
Closing, got it working with the generic template 💯

**Pull request closed without merging**
